# book settings
title: What would other emgerncy stroke teams do? Using explainable machine learning to understand variation in thrombolysis practice
author: Kerry Pearn, Michael Allen, Anna Laws, Richard Everson, and Martin James
#logo: images/logo.png


#only build files specified in table of contents file
only_build_toc_files: true

execute:
  execute_notebooks: 'off' #cache output from .ipynb files for faster build or use auto
  timeout: -1 #no time restriction on notebook execution
  
launch_buttons:
  notebook_interface        : classic  
  binderhub_url             : ""
  
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
