name: samuel2
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib=3.4
  - numpy
  - pip
  - pandas
  - python=3.8
  - scikit-learn
  - tensorflow-gpu=2.4
  - xgboost=1.5
  - pip:
    - graphviz
    - imbalanced-learn
    - pydot
    - shap
    - optuna
